name: MythicProjectiles
version: '1.1-SNAPSHOT'
main: cl.nightcore.mythicProjectiles.MythicProjectiles
api-version: '1.21'
depend: [AuraSkills, PlaceholderAPI, CommandAPI]
softdepend: [MythicMobs, ExcellentEnchants]

commands:
  moblevels:
    description: Comando general
    usage: /getscroll reload